// Generated by CoffeeScript 1.3.3

Ext.setup({
  icon: "icon.png",
  glossOnIcon: false,
  tabletStartupScreen: "tablet_startup.png",
  phoneStartupScreen: "phone_startup.png",
  onReady: function() {
    return Ext.Msg.prompt("Name", "Please enter your name:", function(btn, text) {
      return btn === "ok";
    });
  }
});
